{% set name = "mkdocs-include-markdown-plugin" %}
{% set version = "4.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mkdocs_include_markdown_plugin-{{ version }}.tar.gz
  sha256: 0b98f8877a6e262a91024dae0d40597b04ebe9175f5dfdfa5796a9068e24458a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<3.12
    - hatchling
    - pip
  run:
    - python >=3.7,<3.12

test:
  imports:
    - mkdocs_include_markdown_plugin
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/mkdocs-include-markdown-plugin
  summary: Mkdocs Markdown includer plugin.
  dev_url: https://github.com/mondeja/mkdocs-include-markdown-plugin
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maresb
